services:
  backend:
    image: s237404/mern-backend:1.0
    ports:
      - "5000:5000"

  frontend:
    image: s237404/mern-frontend:1.0
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:7
